services:

  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis


  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: aichat
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aichat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"


volumes:

  postgres_data: